# Generated by Django 3.0.3 on 2020-02-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200229_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='documento',
            new_name='documento_identificacao',
        ),
    ]
