# Generated by Django 3.0.3 on 2020-02-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
